spring.datasource.url=jdbc:postgresql://localhost:5432/saep_agendamento_db?charSet=UTF-8
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true