spring.application.name=backend

# informações sobre o Banco de Dados [Entrega 3]
spring.datasource.url=jdbc:postgresql://localhost:5432/saep_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Jpa - automação da criação das tabelas do BD
spring.jpa.hibernate.ddl-auto=update
#mostra o sql no terminal
spring.jpa.show-sql=true
#utlização de termos especificos do PostgresSQL para otimizar consultas
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
